apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: candycrush-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/teodor1006/CandyCrush-CICD-GitOps.git
    targetRevision: HEAD
    path: ./

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
