apiVersion: apps/v1
kind: Deployment 
metadata:
  name: candycrush
spec:
  replicas: 2
  selector:
    matchLabels:
      app: candycrush
  template:
    metadata:
      labels:
        app: candycrush
    spec:
      containers:
        - name: candycrush
          image: "<your-ecr-repo-uri>"
          ports:
          - containerPort: 3000