apiVersion: apps/v1
kind: Deployment 
metadata:
  name: candycrush
spec:
  replicas: 2
  selector:
    matchLabels:
      app: candycrush
  template:
    metadata:
      labels:
        app: candycrush
    spec:
      containers:
        - name: candycrush
          image: "865893227318.dkr.ecr.us-east-1.amazonaws.com/candycrush"
          ports:
          - containerPort: 3000